# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1115, 692)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnClasificar = QtWidgets.QPushButton(self.centralwidget)
        self.btnClasificar.setGeometry(QtCore.QRect(780, 480, 281, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btnClasificar.setFont(font)
        self.btnClasificar.setObjectName("btnClasificar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 691, 571))
        self.label.setTabletTracking(False)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../prueba.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.lblNombre = QtWidgets.QLabel(self.centralwidget)
        self.lblNombre.setGeometry(QtCore.QRect(780, 580, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblNombre.setFont(font)
        self.lblNombre.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblNombre.setAlignment(QtCore.Qt.AlignCenter)
        self.lblNombre.setObjectName("lblNombre")
        self.txtEntrada = QtWidgets.QLineEdit(self.centralwidget)
        self.txtEntrada.setGeometry(QtCore.QRect(780, 330, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtEntrada.setFont(font)
        self.txtEntrada.setAlignment(QtCore.Qt.AlignCenter)
        self.txtEntrada.setObjectName("txtEntrada")
        self.txtSalida = QtWidgets.QLineEdit(self.centralwidget)
        self.txtSalida.setGeometry(QtCore.QRect(780, 410, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtSalida.setFont(font)
        self.txtSalida.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSalida.setObjectName("txtSalida")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1115, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.btnClasificar, self.txtEntrada)
        MainWindow.setTabOrder(self.txtEntrada, self.txtSalida)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Red Neuronal Unicapa"))
        self.btnClasificar.setText(_translate("MainWindow", "Clasificar"))
        self.lblNombre.setText(_translate("MainWindow", "Herrada Serrano Jorge Luis"))
        self.txtEntrada.setText(_translate("MainWindow", "entradas1.csv"))
        self.txtSalida.setText(_translate("MainWindow", "salidas1.csv"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
